name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history required for comparison

      - name: Validate branch is up to date
        run: |
          git fetch origin ${{ github.ref_name }}
          LOCAL=$(git rev-parse HEAD)
          REMOTE=$(git rev-parse origin/${{ github.ref_name }})

          if [ "$LOCAL" != "$REMOTE" ]; then
            if [ "${{ github.event_name }}" = "push" ]; then
              echo "❌ The local branch is behind origin/${{ github.ref_name }}."
              echo "Please push the latest changes before running the build."
              exit 1
            else
              echo "::warning::⚠️ Branch is behind origin/${{ github.ref_name }} — please rebase before merging."
            fi
          else
            echo "✅ Branch is up to date with origin/${{ github.ref_name }}."
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven (skip tests for now)
        run: mvn -B -ntp -Dmaven.test.skip=true clean package

      - name: Archive test reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/**/*
            **/target/failsafe-reports/**/*
          if-no-files-found: ignore